/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package troyrenaudgr12pat;

import java.awt.print.Book;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author troyr
 */
public class AddNewProductUI extends javax.swing.JFrame {

    /**
     * Creates new form AddNewProductUI
     */
    public AddNewProductUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newBarcodeTF = new javax.swing.JTextField();
        newProductNameTF = new javax.swing.JTextField();
        newExpiryDatePicker = new com.github.lgooddatepicker.components.DatePicker();
        btnBack = new javax.swing.JButton();
        newCategoryTF = new javax.swing.JTextField();
        newQuantityTF = new javax.swing.JTextField();
        insertButton1 = new javax.swing.JButton();
        helpButton3 = new javax.swing.JButton();
        newProductName = new javax.swing.JLabel();
        newCategory = new javax.swing.JLabel();
        newBarcode = new javax.swing.JLabel();
        newPrice = new javax.swing.JLabel();
        newQuantity = new javax.swing.JLabel();
        newExpiryDate = new javax.swing.JLabel();
        newPriceTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newBarcodeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBarcodeTFActionPerformed(evt);
            }
        });

        newProductNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductNameTFActionPerformed(evt);
            }
        });

        btnBack.setText("←");
        btnBack.setBackground(new java.awt.Color(204, 204, 255));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        newQuantityTF.setToolTipText("ISBN Format: ISBN-XX XXX-X-XXXXX-XXX-X");
        newQuantityTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newQuantityTFActionPerformed(evt);
            }
        });

        insertButton1.setText("Insert");
        insertButton1.setBackground(new java.awt.Color(255, 153, 0));
        insertButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButton1ActionPerformed(evt);
            }
        });

        helpButton3.setText("Help");
        helpButton3.setBackground(new java.awt.Color(255, 153, 153));
        helpButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButton3ActionPerformed(evt);
            }
        });

        newProductName.setText("Product Name:");

        newCategory.setText("Category:");

        newBarcode.setText("Barcode:");

        newPrice.setText("Price:");

        newQuantity.setText("Quantity:");

        newExpiryDate.setText("Expiry Date:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(insertButton1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(newQuantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(152, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newQuantity, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(newPrice, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(newBarcode, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(newCategory, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(newProductName, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(newCategoryTF, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(newBarcodeTF, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(newPriceTF, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(newProductNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newExpiryDate)
                                .addGap(77, 77, 77)
                                .addComponent(newExpiryDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(35, 35, 35))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(330, 330, 330)
                    .addComponent(helpButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 10, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newProductName)
                    .addComponent(newProductNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newCategoryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCategory))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newBarcodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBarcode))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newQuantityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newQuantity))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newExpiryDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newExpiryDate))
                .addGap(43, 43, 43)
                .addComponent(insertButton1)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnBack)
                        .addComponent(helpButton3))
                    .addGap(0, 327, Short.MAX_VALUE)))
        );

        newQuantityTF.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newBarcodeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBarcodeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newBarcodeTFActionPerformed

    private void newProductNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProductNameTFActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        LandingPageUI lp = new LandingPageUI();
        lp.setVisible(true);
        this.dispose();
        // Handle the action when the "Back" button is clicked.
        // It opens the LandingPageUI and closes the current window.
    }//GEN-LAST:event_btnBackActionPerformed

    private void newQuantityTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newQuantityTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newQuantityTFActionPerformed

    private void insertButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButton1ActionPerformed
        String pn = newProductNameTF.getText().trim();
        String category = newCategoryTF.getText().trim();
        String barcode = newBarcodeTF.getText().trim();
        String priceText = newPriceTF.getText().trim();
        String quantityText = newQuantityTF.getText().trim();
        //extracts text from four different text fields and stores that text in four separate String variables
        //.trim helps .isEmpty to work by trimming spaces and seeing if values were left out

        if (pn.isEmpty() || category.isEmpty() || barcode.isEmpty() || priceText.isEmpty() || quantityText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "All text fields must be entered.");
            return;
        }
        // Check if any of the text fields are empty
        //this is an if statement to see what if the data will be returned true/false - and then follow up with commands like a message pop-up

        double price;
        try {
            price = Double.parseDouble(priceText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid price format. Please enter a valid number.");
            return;
            //makes sure that the price entered is in the right format and if not it displays a message
        }

        int quantity;
        try {
            quantity = Integer.parseInt(quantityText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid quantity format. Please enter a valid integer.");
            return;
            // Makes sure that the quantity entered is in the right format and if not it displays a message
        }

        LocalDate publicationDate = newExpiryDatePicker.getDate();
        Product newProduct = new Product(pn, category, barcode, price, quantity, publicationDate);
        //updates to the current editted data

        if (!isValidBarcode(barcode)) {
            JOptionPane.showMessageDialog(null, "Invalid barcode format. Please enter a valid barcode.");
            return;
            //runs the isValidBarcode code an return message if false
        }

        //Insert the new Book using BookHandler
        DataHandler dh = new DataHandler();
        dh.insertNewProduct(newProduct);

        clearTextFields(); //runs the clearing of the fields
    }//GEN-LAST:event_insertButton1ActionPerformed

    private void clearTextFields() {
        newProductNameTF.setText("");
        newCategoryTF.setText("");
        newBarcodeTF.setText("");
        newPriceTF.setText("");
        newQuantityTF.setText("");
        newExpiryDatePicker.setDate(null);
        //method is used to reset the values of text fields
    }

    private boolean isValidBarcode(String barcode) {
        return barcode.matches("\\d{12}");
        //makes sure barcode is in the right format and no letters
        //https://stackoverflow.com/questions/21426481/what-does-the-regex-d3-d-mean
    }

    private void helpButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButton3ActionPerformed
        JOptionPane.showMessageDialog(null, "- Type values in the blocks" + "\n" + "- Then click Insert to create a product on the system");
        //creates a message box that helps the user with what the page does
    }//GEN-LAST:event_helpButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewProductUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewProductUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewProductUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewProductUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewProductUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton helpButton3;
    private javax.swing.JButton insertButton1;
    private javax.swing.JLabel newBarcode;
    private javax.swing.JTextField newBarcodeTF;
    private javax.swing.JLabel newCategory;
    private javax.swing.JTextField newCategoryTF;
    private javax.swing.JLabel newExpiryDate;
    private com.github.lgooddatepicker.components.DatePicker newExpiryDatePicker;
    private javax.swing.JLabel newPrice;
    private javax.swing.JTextField newPriceTF;
    private javax.swing.JLabel newProductName;
    private javax.swing.JTextField newProductNameTF;
    private javax.swing.JLabel newQuantity;
    private javax.swing.JTextField newQuantityTF;
    // End of variables declaration//GEN-END:variables
}
