/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package troyrenaudgr12pat;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * This class displays the sales records UI for admin users. It shows collected
 * tabs with details like TabID, CustomerID, Balance, Paid, and Collected.
 */
public class AdminSalesRecordsUI extends javax.swing.JFrame {

    private User adminUser;
    private Customer currentCustomer;
    private int selected;
    private ArrayList<Tab> collectedTabs;

    /**
     * Creates a new AdminSalesRecordsUI. Initializes the components and
     * populates the collected tabs table.
     *
     * @param adminUser the current admin user
     * @param c the current customer
     */
    public AdminSalesRecordsUI(User adminUser, Customer c) {
        initComponents();
        this.adminUser = adminUser;
        this.currentCustomer = c;
        populateCollectedTabsTable();
    }

    /**
     * Populates the collected tabs table with data from the database. It
     * retrieves collected tabs and adds them to the table model.
     */
    private void populateCollectedTabsTable() {
        DataHandler dh = new DataHandler();
        collectedTabs = dh.getAllCollectedTabs();
        DefaultTableModel dtm = (DefaultTableModel) tblTabs.getModel();
        dtm.setRowCount(0); // Clear existing rows

        Object[] tabRow = new Object[5];
        for (int i = 0; i < collectedTabs.size(); i++) {
            tabRow[0] = "" + collectedTabs.get(i).getTabID();
            tabRow[1] = "" + collectedTabs.get(i).getCustomer().getCustomerID();
            tabRow[2] = "" + collectedTabs.get(i).getBalance();
            tabRow[3] = collectedTabs.get(i).isPaid();
            tabRow[4] = collectedTabs.get(i).isCollected();
            dtm.addRow(tabRow);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTabs = new javax.swing.JTable();
        asrHelpBtn = new javax.swing.JButton();
        apmImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1315, 835));
        setResizable(false);
        getContentPane().setLayout(null);

        btnBack.setBackground(new java.awt.Color(204, 204, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(20, 20, 70, 30);

        tblTabs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblTabs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TabID", "CustomerID", "Balance", "Paid", "Collected"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTabs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTabsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTabs);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(110, 160, 1040, 490);

        asrHelpBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        asrHelpBtn.setText("Help");
        asrHelpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asrHelpBtnActionPerformed(evt);
            }
        });
        getContentPane().add(asrHelpBtn);
        asrHelpBtn.setBounds(1210, 20, 70, 30);

        apmImage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        apmImage.setForeground(java.awt.Color.white);
        apmImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\troyr\\Dropbox\\School Work\\IT\\TroyRenaudGr12PAT\\Troy_Gr_12_PAT_Images\\milad-fakurian-bexwsdM5BCw-unsplash.jpg")); // NOI18N
        getContentPane().add(apmImage);
        apmImage.setBounds(-1140, -160, 2700, 960);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles the action when the "Back" button is clicked. Opens the
     * AdminDashboardUI and closes the current window.
     *
     * @param evt the action event triggered by clicking the button
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        AdminDashboardUI adb = new AdminDashboardUI(adminUser, currentCustomer);
        adb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * Handles mouse click events on the tabs table. Updates the selected index
     * with the clicked row.
     *
     * @param evt the mouse event triggered by clicking a table row
     */
    private void tblTabsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTabsMouseClicked
        selected = tblTabs.getSelectedRow();
    }//GEN-LAST:event_tblTabsMouseClicked

    /**
     * Displays a help message dialog to guide users on how to use the Sales Records page.
     *
     * @param evt action event triggered by clicking the help button
     */
    private void asrHelpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asrHelpBtnActionPerformed
        String helpMessage = "1. This interface allows admin users to view sales records of collected tabs.\n\n"
                + "2. The table displays the following information:\n"
                + "   - TabID: The unique identifier for each tab.\n"
                + "   - CustomerID: The ID of the customer associated with the tab.\n"
                + "   - Balance: The remaining balance for the tab.\n"
                + "   - Paid: Whether the tab has been fully paid (True/False).\n"
                + "   - Collected: Whether the tab has been collected by the customer (True/False).\n\n"
                + "3. Editing Tabs:\n"
                + "   - You can edit the 'Paid' and 'Collected' columns by clicking on the respective cells.\n"
                + "   - After editing, ensure that your changes are properly saved.\n\n"
                + "4. Navigation:\n"
                + "   - To return to the Admin Dashboard, click the 'Back' button.\n\n"
                + "If you have any further questions, please contact support.";

        JOptionPane.showMessageDialog(null, helpMessage, "Admin Sales Records Help", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_asrHelpBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSalesRecordsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSalesRecordsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSalesRecordsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSalesRecordsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AdminSalesRecordsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apmImage;
    private javax.swing.JButton asrHelpBtn;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTabs;
    // End of variables declaration//GEN-END:variables
}
