/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package troyrenaudgr12pat;

/**
 *
 * @author troyr
 */
public class AdminDashboardUI extends javax.swing.JFrame {

    private User adminUser;
    private Customer currentCustomer;

    /**
     * Creates new form AdminDashboardUI
     */
    public AdminDashboardUI(User adminUser, Customer c) {
        initComponents();
        this.adminUser = adminUser;
        currentCustomer = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageProductsBtn = new javax.swing.JButton();
        manageCustomersBtn = new javax.swing.JButton();
        salesRecordsBtn = new javax.swing.JButton();
        manageUsersBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        manageProductsBtn.setText("Manage Products");
        manageProductsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProductsBtnActionPerformed(evt);
            }
        });

        manageCustomersBtn.setText("Manage Customers");
        manageCustomersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomersBtnActionPerformed(evt);
            }
        });

        salesRecordsBtn.setText("Sales Records");
        salesRecordsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesRecordsBtnActionPerformed(evt);
            }
        });

        manageUsersBtn.setText("Manage Users");
        manageUsersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUsersBtnActionPerformed(evt);
            }
        });

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(204, 204, 255));
        btnBack.setText("←");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(1026, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageUsersBtn)
                    .addComponent(salesRecordsBtn)
                    .addComponent(manageCustomersBtn)
                    .addComponent(manageProductsBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(logoutBtn)))
                .addGap(149, 149, 149))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack)
                .addGap(45, 45, 45)
                .addComponent(manageProductsBtn)
                .addGap(18, 18, 18)
                .addComponent(manageCustomersBtn)
                .addGap(18, 18, 18)
                .addComponent(salesRecordsBtn)
                .addGap(18, 18, 18)
                .addComponent(manageUsersBtn)
                .addGap(18, 18, 18)
                .addComponent(logoutBtn)
                .addContainerGap(545, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        LoginPageUI lp = new LoginPageUI();
        lp.setVisible(true);
        this.dispose();
//         Handle the action when the "Back" button is clicked.
//         It opens the LandingPageUI and closes the current window.
    }//GEN-LAST:event_btnBackActionPerformed

    private void manageProductsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProductsBtnActionPerformed
        ProductManagementUI productsUI = new ProductManagementUI(adminUser, currentCustomer);
        productsUI.setVisible(true);
    }//GEN-LAST:event_manageProductsBtnActionPerformed

    private void manageCustomersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomersBtnActionPerformed
        CustomerManagementUI customersUI = new CustomerManagementUI(adminUser, currentCustomer);
        customersUI.setVisible(true);
    }//GEN-LAST:event_manageCustomersBtnActionPerformed

    private void salesRecordsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesRecordsBtnActionPerformed
        SalesRecordsUI salesUI = new SalesRecordsUI();
        salesUI.setVisible(true);
    }//GEN-LAST:event_salesRecordsBtnActionPerformed

    private void manageUsersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUsersBtnActionPerformed
        UserManagementUI usersUI = new UserManagementUI(adminUser, currentCustomer);
        usersUI.setVisible(true);
    }//GEN-LAST:event_manageUsersBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        new LoginPageUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//
//}
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AdminDashboardUI.class  
//
//.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//
//} catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AdminDashboardUI.class  
//
//.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//
//} catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AdminDashboardUI.class  
//
//.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//
//} catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AdminDashboardUI.class  
//
//.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AdminDashboardUI().setVisible(true);
//            }
//        });
 //   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton manageCustomersBtn;
    private javax.swing.JButton manageProductsBtn;
    private javax.swing.JButton manageUsersBtn;
    private javax.swing.JButton salesRecordsBtn;
    // End of variables declaration//GEN-END:variables
}
