/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package troyrenaudgr12pat;

import javax.swing.JOptionPane;

/**
 * This class manages the Admin buttons in the UI for navigation.
 */
public class AdminDashboardUI extends javax.swing.JFrame {

    private User adminUser;
    private Customer currentCustomer;

    /**
     * Constructor for the AdminDashboardUI class. Initializes the form and sets
     * the admin user and current customer.
     *
     * @param adminUser the User object representing the admin
     * @param c the Customer object representing the current customer
     */
    public AdminDashboardUI(User adminUser, Customer c) {
        initComponents();
        this.adminUser = adminUser;
        currentCustomer = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageProductsBtn = new javax.swing.JButton();
        manageCustomersBtn = new javax.swing.JButton();
        salesRecordsBtn = new javax.swing.JButton();
        manageUsersBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        adbHelpBtn = new javax.swing.JButton();
        adbImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1315, 835));
        setResizable(false);
        getContentPane().setLayout(null);

        manageProductsBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        manageProductsBtn.setText("Manage Products");
        manageProductsBtn.setPreferredSize(new java.awt.Dimension(300, 100));
        manageProductsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProductsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(manageProductsBtn);
        manageProductsBtn.setBounds(500, 90, 300, 100);

        manageCustomersBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        manageCustomersBtn.setText("Manage Customers");
        manageCustomersBtn.setPreferredSize(new java.awt.Dimension(300, 100));
        manageCustomersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomersBtnActionPerformed(evt);
            }
        });
        getContentPane().add(manageCustomersBtn);
        manageCustomersBtn.setBounds(500, 210, 300, 100);

        salesRecordsBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        salesRecordsBtn.setText("Sales Records");
        salesRecordsBtn.setPreferredSize(new java.awt.Dimension(300, 100));
        salesRecordsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesRecordsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(salesRecordsBtn);
        salesRecordsBtn.setBounds(500, 330, 300, 100);

        manageUsersBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        manageUsersBtn.setText("Manage Users");
        manageUsersBtn.setPreferredSize(new java.awt.Dimension(300, 100));
        manageUsersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUsersBtnActionPerformed(evt);
            }
        });
        getContentPane().add(manageUsersBtn);
        manageUsersBtn.setBounds(500, 450, 300, 100);

        logoutBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.setPreferredSize(new java.awt.Dimension(300, 100));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutBtn);
        logoutBtn.setBounds(500, 570, 300, 100);

        btnBack.setBackground(new java.awt.Color(204, 204, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(20, 20, 70, 30);

        adbHelpBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adbHelpBtn.setText("Help");
        adbHelpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adbHelpBtnActionPerformed(evt);
            }
        });
        getContentPane().add(adbHelpBtn);
        adbHelpBtn.setBounds(1220, 20, 60, 30);

        adbImage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adbImage.setForeground(java.awt.Color.white);
        adbImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\troyr\\Dropbox\\School Work\\IT\\TroyRenaudGr12PAT\\Troy_Gr_12_PAT_Images\\milad-fakurian-9xCvw544PWQ-unsplash.jpg")); // NOI18N
        getContentPane().add(adbImage);
        adbImage.setBounds(-2340, 0, 3730, 3700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Action performed when the "Back" button is clicked. This method opens the
     * LoginPageUI and disposes of the current window.
     *
     * @param evt the event that triggers this action (button click)
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        LoginPageUI lp = new LoginPageUI();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * Action performed when "Manage Products" button is clicked. This method
     * opens the AdminProductManagementUI and closes the current window.
     *
     * @param evt the event that triggers this action (button click)
     */
    private void manageProductsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProductsBtnActionPerformed
        AdminProductManagementUI pm = new AdminProductManagementUI(adminUser, currentCustomer);
        pm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manageProductsBtnActionPerformed

    /**
     * Action performed when "Manage Customers" button is clicked. This method
     * opens the AdminCustomerManagementUI and closes the current window.
     *
     * @param evt the event that triggers this action (button click)
     */
    private void manageCustomersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomersBtnActionPerformed
        AdminCustomerManagementUI cm = new AdminCustomerManagementUI(adminUser, currentCustomer);
        cm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manageCustomersBtnActionPerformed

    /**
     * Action performed when "Sales Records" button is clicked. This method
     * opens the AdminSalesRecordsUI and closes the current window.
     *
     * @param evt the event that triggers this action (button click)
     */
    private void salesRecordsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesRecordsBtnActionPerformed
        AdminSalesRecordsUI sr = new AdminSalesRecordsUI(adminUser, currentCustomer);
        sr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salesRecordsBtnActionPerformed

    /**
     * Action performed when "Manage Users" button is clicked. This method opens
     * the AdminUserManagementUI and closes the current window.
     *
     * @param evt the event that triggers this action (button click)
     */
    private void manageUsersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUsersBtnActionPerformed
        AdminUserManagementUI um = new AdminUserManagementUI(adminUser, currentCustomer);
        um.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_manageUsersBtnActionPerformed

    /**
     * Action performed when "Logout" button is clicked. This method logs the
     * user out by opening the LoginPageUI and closing the current window.
     *
     * @param evt the event that triggers this action (button click)
     */
    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        new LoginPageUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * Displays a help message dialog to guide users on how to navigate and use
     * the Admin Dashboard.
     *
     * @param evt action event triggered by clicking the help button
     */
    private void adbHelpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adbHelpBtnActionPerformed
        String helpMessage = "Welcome to the Admin Dashboard!\n\n"
                + "1. Manage Products: Click the 'Manage Products' button to add, edit, or remove products from the inventory.\n\n"
                + "2. Manage Customers: Click 'Manage Customers' to view, add, edit, or remove customers from the system.\n\n"
                + "3. Sales Records: Click 'Sales Records' to view and manage sales data, including tab collections and payments.\n\n"
                + "4. Manage Users: Use this option to add, edit, or remove users who can access the system.\n\n"
                + "5. Logout: Click 'Logout' to log out and return to the login page.\n\n"
                + "6. Back Button: Click the '←' button to return to the previous screen.\n\n"
                + "If you encounter any issues or need further assistance, please contact support.";

        JOptionPane.showMessageDialog(null, helpMessage, "Admin Dashboard Help", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_adbHelpBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AdminDashboardUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adbHelpBtn;
    private javax.swing.JLabel adbImage;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton manageCustomersBtn;
    private javax.swing.JButton manageProductsBtn;
    private javax.swing.JButton manageUsersBtn;
    private javax.swing.JButton salesRecordsBtn;
    // End of variables declaration//GEN-END:variables
}
