/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package troyrenaudgr12pat;

import javax.swing.JOptionPane;

/**
 * This is the Customer Selection User Interface class. It allows the user to
 * select options related to customers.
 *
 * It has buttons to view new or previous customers, collections, or kitchen
 * display.
 */
public class CustomerSelectionUI extends javax.swing.JFrame {

    private User currentUser;
    private Customer currentCustomer;

    /**
     * Constructor for CustomerSelectionUI. Initializes the form with the given
     * user and customer.
     *
     * @param u the user
     * @param c the customer
     */
    public CustomerSelectionUI(User u, Customer c) {
        initComponents();
        currentUser = u;
        currentCustomer = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newCustomerBtn = new javax.swing.JButton();
        previousCustomerBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        collectionsBtn = new javax.swing.JButton();
        kitchenDisplayBtn = new javax.swing.JButton();
        csHelpBtn = new javax.swing.JButton();
        csImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1315, 835));
        setPreferredSize(new java.awt.Dimension(1300, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1300, 800));
        getContentPane().setLayout(null);

        newCustomerBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newCustomerBtn.setText("New Customer");
        newCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCustomerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(newCustomerBtn);
        newCustomerBtn.setBounds(520, 100, 290, 100);

        previousCustomerBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        previousCustomerBtn.setText("Previous Customer");
        previousCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousCustomerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(previousCustomerBtn);
        previousCustomerBtn.setBounds(520, 220, 290, 100);

        backBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(20, 20, 70, 30);

        collectionsBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        collectionsBtn.setText("Collections");
        collectionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectionsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(collectionsBtn);
        collectionsBtn.setBounds(520, 590, 290, 100);

        kitchenDisplayBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kitchenDisplayBtn.setText("Kitchen Display");
        kitchenDisplayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitchenDisplayBtnActionPerformed(evt);
            }
        });
        getContentPane().add(kitchenDisplayBtn);
        kitchenDisplayBtn.setBounds(520, 470, 290, 100);

        csHelpBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        csHelpBtn.setText("Help");
        csHelpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csHelpBtnActionPerformed(evt);
            }
        });
        getContentPane().add(csHelpBtn);
        csHelpBtn.setBounds(1210, 20, 60, 30);

        csImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\troyr\\Dropbox\\School Work\\IT\\TroyRenaudGr12PAT\\Troy_Gr_12_PAT_Images\\faded_gallery-7stSlxNAmfc-unsplash.jpg")); // NOI18N
        csImage.setToolTipText("");
        getContentPane().add(csImage);
        csImage.setBounds(0, 0, 1300, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Action method for "New Customer" button. Opens the NewCustomerUI window
     * and closes this window.
     *
     * @param evt the action event
     */
    private void newCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCustomerBtnActionPerformed
        NewCustomerUI nc = new NewCustomerUI(currentUser, currentCustomer);
        nc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_newCustomerBtnActionPerformed

    /**
     * Action method for "Previous Customer" button. Opens the
     * PreviousCustomerUI window and closes this window.
     *
     * @param evt the action event
     */
    private void previousCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousCustomerBtnActionPerformed
        PreviousCustomerUI pc = new PreviousCustomerUI(currentUser, currentCustomer);
        pc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_previousCustomerBtnActionPerformed

    /**
     * Action method for "Back" button. Opens the LoginPageUI window and closes
     * this window.
     *
     * @param evt the action event
     */
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        LoginPageUI lp1 = new LoginPageUI();
        lp1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * Action method for "Collections" button. Opens the CollectionsUI window
     * and closes this window.
     *
     * @param evt the action event
     */
    private void collectionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectionsBtnActionPerformed
        CollectionsUI c = new CollectionsUI(currentUser, currentCustomer);
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_collectionsBtnActionPerformed

    /**
     * Action method for "Kitchen Display" button. Opens the KitchenDisplayUI
     * window and closes this window.
     *
     * @param evt the action event
     */
    private void kitchenDisplayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitchenDisplayBtnActionPerformed
        KitchenDisplayUI kd = new KitchenDisplayUI(currentUser, currentCustomer);
        kd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kitchenDisplayBtnActionPerformed

    /**
     * Displays a help message dialog to guide users on how to use the customer
     * selection interface.
     *
     * @param evt action event triggered by clicking the help button
     */
    private void csHelpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csHelpBtnActionPerformed
        String helpMessage = "Welcome to the Customer Selection Interface!\n\n"
                + "1. This interface allows you to manage customer interactions.\n\n"
                + "2. Available Options:\n"
                + "   - **New Customer**: Click this button to add a new customer to the system.\n"
                + "   - **Previous Customer**: Select this option to view or manage previous customers.\n"
                + "   - **Collections**: Use this to access the collections management interface.\n"
                + "   - **Kitchen Display**: This option opens the kitchen display interface for order management.\n\n"
                + "3. Navigation:\n"
                + "   - To return to the previous screen, click the 'Back' button.\n\n"
                + "4. Help:\n"
                + "   - For assistance, you can click the 'Help' button at any time to view this message.\n\n"
                + "If you have further questions, please consult the user manual or contact support.";

        JOptionPane.showMessageDialog(null, helpMessage, "Customer Selection Help", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_csHelpBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerSelectionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerSelectionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerSelectionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerSelectionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CustomerSelectionUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton collectionsBtn;
    private javax.swing.JButton csHelpBtn;
    private javax.swing.JLabel csImage;
    private javax.swing.JButton kitchenDisplayBtn;
    private javax.swing.JButton newCustomerBtn;
    private javax.swing.JButton previousCustomerBtn;
    // End of variables declaration//GEN-END:variables
}
