/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package troyrenaudgr12pat;

import java.util.HashMap;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author troyr
 */
public class SelectProductsForTabUI extends javax.swing.JFrame {

    private User currentUser;
    private Customer currentCustomer;
    private Tab currentTab;
    private ArrayList<Product> allProducts;
    private HashMap<String, Product> productActionMap = new HashMap<>(); //helped with hashmap, https://stackoverflow.com/questions/16819368/hashmap-in-java

    /**
     * Creates new form LandingPage
     */
    public SelectProductsForTabUI(User u, Customer c) {
        initComponents();
        currentUser = u;
        currentCustomer = c;
        createNewTab();
        loadProducts();
        populateExistingTabs();
    }

    private void createNewTab() {
        DataHandler dh = new DataHandler();
        int newTabID = dh.generateNewTabID(); // Implement this method in DataHandler
        currentTab = new Tab(newTabID, currentCustomer, 0.0);
        dh.addTab(currentTab); // Save the new tab
    }

    private void loadProducts() {
        DataHandler dh = new DataHandler();
        allProducts = dh.getAllProducts(); // Retrieve all products
    }

    private void populateExistingTabs() {
        // Assumes existing JPanels are named accordingly: bunsPanel, burgersPanel, pizzasPanel, etc.
        JPanel[] categoryPanels = {bunsRollsPanel, burgersPanel, pizzasPanel, toastedSandwichesPanel, snacksPanel};
        String[] categories = {"Buns & Rolls", "Burgers", "Pizzas", "Toasted Sandwiches", "Snacks"};

        for (int i = 0; i < categories.length; i++) {
            String category = categories[i];
            JPanel panel = categoryPanels[i];
            panel.setLayout(new GridLayout(0, 1)); // Ensure layout for adding buttons

            for (Product product : allProducts) {
                if (product.getCategory().equals(category)) {
                    JButton productButton = new JButton(product.getProductName() + " - R" + product.getPrice());
                    String actionCommand = "product-" + product.getProductID(); // Ensure unique command
                    productButton.setActionCommand(actionCommand);
                    productActionMap.put(actionCommand, product); //helps with productActionMap, .addActionListener, etc, https://stackoverflow.com/questions/7253712/java-swing-using-actionmap
                    panel.add(productButton);
                    productButton.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            handleProductButtonAction(e);
                        }
                    });
                }
            }
        }

        // Refresh the UI after adding components
        for (JPanel panel : categoryPanels) {
            panel.revalidate();
            panel.repaint();
        }
    }

    private void handleProductButtonAction(ActionEvent e) {
        String actionCommand = e.getActionCommand();
        Product product = productActionMap.get(actionCommand);
        if (product != null) {
            addProductToTab(product);
        }
    }

    private void addProductToTab(Product p) {
        currentTab.addProduct(p, 1); // Assuming adding one quantity at a time
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageTabsBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        productTabs = new javax.swing.JTabbedPane();
        bunsRollsPanel = new javax.swing.JPanel();
        burgersPanel = new javax.swing.JPanel();
        pizzasPanel = new javax.swing.JPanel();
        toastedSandwichesPanel = new javax.swing.JPanel();
        snacksPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        manageTabsBtn.setText("Manage Tabs");
        manageTabsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageTabsBtnActionPerformed(evt);
            }
        });

        backBtn.setText("←");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bunsRollsPanelLayout = new javax.swing.GroupLayout(bunsRollsPanel);
        bunsRollsPanel.setLayout(bunsRollsPanelLayout);
        bunsRollsPanelLayout.setHorizontalGroup(
            bunsRollsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 993, Short.MAX_VALUE)
        );
        bunsRollsPanelLayout.setVerticalGroup(
            bunsRollsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        productTabs.addTab("Buns & Rolls", bunsRollsPanel);

        javax.swing.GroupLayout burgersPanelLayout = new javax.swing.GroupLayout(burgersPanel);
        burgersPanel.setLayout(burgersPanelLayout);
        burgersPanelLayout.setHorizontalGroup(
            burgersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 993, Short.MAX_VALUE)
        );
        burgersPanelLayout.setVerticalGroup(
            burgersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        productTabs.addTab("Burgers", burgersPanel);

        javax.swing.GroupLayout pizzasPanelLayout = new javax.swing.GroupLayout(pizzasPanel);
        pizzasPanel.setLayout(pizzasPanelLayout);
        pizzasPanelLayout.setHorizontalGroup(
            pizzasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 993, Short.MAX_VALUE)
        );
        pizzasPanelLayout.setVerticalGroup(
            pizzasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        productTabs.addTab("Pizzas", pizzasPanel);

        javax.swing.GroupLayout toastedSandwichesPanelLayout = new javax.swing.GroupLayout(toastedSandwichesPanel);
        toastedSandwichesPanel.setLayout(toastedSandwichesPanelLayout);
        toastedSandwichesPanelLayout.setHorizontalGroup(
            toastedSandwichesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 993, Short.MAX_VALUE)
        );
        toastedSandwichesPanelLayout.setVerticalGroup(
            toastedSandwichesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        productTabs.addTab("Toasted Sandwiches", toastedSandwichesPanel);

        javax.swing.GroupLayout snacksPanelLayout = new javax.swing.GroupLayout(snacksPanel);
        snacksPanel.setLayout(snacksPanelLayout);
        snacksPanelLayout.setHorizontalGroup(
            snacksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 993, Short.MAX_VALUE)
        );
        snacksPanelLayout.setVerticalGroup(
            snacksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        productTabs.addTab("Snacks", snacksPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backBtn)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 1203, Short.MAX_VALUE)
                .addComponent(manageTabsBtn))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(productTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backBtn)
                .addGap(88, 88, 88)
                .addComponent(productTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(manageTabsBtn))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageTabsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageTabsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageTabsBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        CustomerSelectionUI cs = new CustomerSelectionUI(currentUser, currentCustomer);
        cs.setVisible(true);
        this.dispose();
        // Handle the action when the "Back" button is clicked.
        // It opens the SelectProductsForTabUI and closes the current window.
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectProductsForTabUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectProductsForTabUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectProductsForTabUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectProductsForTabUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new SelectProductsForTabUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel bunsRollsPanel;
    private javax.swing.JPanel burgersPanel;
    private javax.swing.JButton manageTabsBtn;
    private javax.swing.JPanel pizzasPanel;
    private javax.swing.JTabbedPane productTabs;
    private javax.swing.JPanel snacksPanel;
    private javax.swing.JPanel toastedSandwichesPanel;
    // End of variables declaration//GEN-END:variables
}
